name: bulb_front_image
dataset_path: /mnt/work/dexIL/Dex_Diffuse/data/bulb_rotate_0903_dp

image_shape: &image_shape [3, 240, 320]
shape_meta:
  obs:
    front_image:
      shape: *image_shape
      type: rgb
    # Relative to the latest observed EE frame when dataset.relative=true.
    ee_pose:
      shape: [9]
      type: low_dim
    # Absolute hand-joint positions.
    hand_joint:
      shape: [22]
      type: low_dim
  action:
    shape: [31]

env_runner:
  _target_: diffusion_policy.env_runner.null_image_runner.NullImageRunner

dataset:
  _target_: diffusion_policy.dataset.bulb_front_image_dataset.BulbFrontImageDataset
  dataset_path: ${task.dataset_path}
  relative: true
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null
