name: sim_hand_mixed

obs_dim: 66
action_dim: 22
data_root: /home/carus/mnt/bigai/Data

mixing:
  probabilities:
    expdata: 0.8
    bulb_tac: 0.2
  samples_per_epoch: null

env_runner:
  _target_: diffusion_policy.env_runner.null_lowdim_runner.NullLowdimRunner

dataset:
  _target_: diffusion_policy.dataset.mixed_lowdim_dataset.MixedLowdimDataset
  datasets:
    expdata:
      _target_: diffusion_policy.dataset.sim_hand_lowdim_dataset.SimHandLowdimDataset
      dataset_path: ${task.data_root}/exp_data
      horizon: ${horizon}
      pad_before: ${eval:'${n_obs_steps}-1'}
      pad_after: ${eval:'${n_pred_action_steps}-1'}
      seed: ${training.seed}
      val_ratio: 0.1
      max_train_episodes: null
    bulb_tac:
      _target_: diffusion_policy.dataset.bulb_tac_lowdim_dataset.BulbTacLowdimDataset
      dataset_path: ${task.data_root}/bulb_tac_80
      horizon: ${horizon}
      pad_before: ${eval:'${n_obs_steps}-1'}
      pad_after: ${eval:'${n_pred_action_steps}-1'}
      seed: ${training.seed}
      val_ratio: 0.1
  probabilities: ${task.mixing.probabilities}
  samples_per_epoch: ${task.mixing.samples_per_epoch}
